### ISSUE TITLE
login: redirect to 404

### ISSUE THREAD

**Issue by bwbroersma** [wolbodo/sympa-docker#2]
The web login on live is broken, it redirects to a `404`:
http://lists.wolbodo.nl/sympa

**Comment by dhrp** [comment]
thanks. 

Is gefixed.

**Comment by dhrp** [comment]
By the way: Cause of issue was  dat de de server was ge-reboot, end dat de fcgiwrapper niet meer de fcgiwrap.sock kon pakken, omdat het bestand nog bestond.
